version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15
    container_name: zap-postgres
    environment:
      POSTGRES_USER: zapuser
      POSTGRES_PASSWORD: zappass
      POSTGRES_DB: zapdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zap-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: zap-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zap-network

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zap-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://zapuser:zappass@postgres:5432/zapdb
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-secret-key-here
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - zap-network
    command: npm run start:dev

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zap-frontend
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - zap-network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  zap-network:
    driver: bridge